// AIInsightCard - Displays AI-generated insights about a candidate
import React from 'react';
import { FiCheck, FiAlertCircle, FiZap } from 'react-icons/fi';

const AIInsightCard = ({ insights }) => {
  if (!insights) return null;

  return (
    <div className="ai-insight-card">
      <div className="insight-header">
      <FiZap className="insight-icon" />
        <h3>AI Insights</h3>
      </div>

      <div className="insights-content">
        {/* Strengths Section */}
        <div className="insight-section strengths">
          <div className="section-header">
            <FiCheck className="section-icon positive" />
            <h4>Strengths</h4>
          </div>
          <ul className="insight-list">
            {insights.strengths.map((strength, index) => (
              <li key={index} className="insight-item">
                <span className="bullet-point"></span>
                {strength}
              </li>
            ))}
          </ul>
        </div>

        {/* Improvement Areas Section */}
        <div className="insight-section improvements">
          <div className="section-header">
            <FiAlertCircle className="section-icon warning" />
            <h4>Areas for Improvement</h4>
          </div>
          <ul className="insight-list">
            {insights.improvements.map((improvement, index) => (
              <li key={index} className="insight-item">
                <span className="bullet-point"></span>
                {improvement}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="insight-footer">
        <p className="ai-disclaimer">
       <FiZap className="insight-icon" />
          These insights are generated by AI based on resume analysis and should be used 
          as guidance alongside human judgment.
        </p>
      </div>
    </div>
  );
};

export default AIInsightCard;
